import type { ThemeDefinition } from './theme.types.ts';

export const darkWorkshop: ThemeDefinition = {
  name: 'dark-workshop',
  displayName: '暗室',
  colors: {
    bgPrimary: '#101113',
    bgSecondary: '#15171A',
    bgTertiary: '#202329',
    border: '#2A2D31',
    textPrimary: '#F2F0EA',
    textSecondary: '#A7A29A',
    textMuted: '#6F716E',
    accent: '#E7B65F',
    accentHover: '#F1C978',
    accentForeground: '#17120A',
    info: '#80A7FF',
    success: '#63D297',
    warning: '#F59E0B',
    error: '#EF4444',
    errorForeground: '#17120A',
    codeBg: '#0B0C0E',
    sourceClaudeCode: '#E8784A',
    sourceCodex: '#10A37F',
    sourceCursor: '#A855F7',
    sourceTrae: '#6366F1',
    sourceCopilot: '#1F6FEB',
    graphEdgeCausedBy: '#D96B57',
    graphEdgeLeadsTo: '#D89A55',
    graphEdgeResolvedBy: '#63D297',
    graphEdgeSimilarTo: '#80A7FF',
    graphEdgeContradicts: '#E7B65F',
    graphEdgeDependsOn: '#A78BFA',
    graphEdgeExtends: '#5EC8C3',
    graphEdgeReferences: '#8B8D87',
    graphProject1: '#D68B66',
    graphProject2: '#CDA75E',
    graphProject3: '#7DBB8F',
    graphProject4: '#77AAA5',
    graphProject5: '#7FA5D8',
    graphProject6: '#998DD1',
    graphProject7: '#C28CC0',
    graphProject8: '#AA9F87',
    graphProject9: '#879AA7',
    graphProject10: '#C97979',
  },
  fonts: {
    display: '"Aptos Display", "HarmonyOS Sans SC", "Microsoft YaHei UI", system-ui, sans-serif',
    body: '"Aptos", "HarmonyOS Sans SC", "Microsoft YaHei UI", "Noto Sans SC", system-ui, sans-serif',
    mono: '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
  },
  radius: '6px',
  density: 'compact',
};
